using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Infrastructure;

namespace WebApplication1.Models
{
    [Table("tDecklistEntries")]   
    public class DecklistEntry
    {
        //in primary key, autogenerated on create
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DecklistId { get; set; }

        [ForeignKey("Deck")]
        public int DeckId  { get; set; }
        public Deck Deck { get; set; }

        //in primary key 
        [ForeignKey("Card")]
        public int CardId { get; set; }
        public Card Card { get; set; }

        //in primary key
        public int Quantity { get; set; }

        //in primary key
        //on update increment for each unchanged, plus insert new ones with updated index
        //[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Index { get; set; }
        public string Comment { get; set; }

        //in primary key
        public bool IsSideboard { get; set; }
    }
}
